### ISSUE TITLE
Windows defender detects it as a virus

### ISSUE THREAD

**Issue by MrAlexEsisteGia** [ItsBranK/BranksMod#2]
![image](https://user-images.githubusercontent.com/24595840/56378729-2ae18e00-620e-11e9-9d58-1c619a102cb0.png)

**Comment by ItsBranK** [comment]
Yeah AV's get confused and don't know when DLL injectors are good or bad. I'll obfuscate it in the next release and hope that fixes it.

**Comment by MrAlexEsisteGia** [comment]
I suggest to flag the false positive and not obfuscate because maybe some av's can be more allarmed from the unknown activity (maybe???)
